theme: minima

# Site settings
title: My GitHub Pages Site
description: A simple site built using GitHub Pages
url: "https://fomi-ann.github.io"
baseurl: ""  # Only for project pages

# Markdown processing settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

# Other settings
lsi: false
safe: true
incremental: false
gist:
  noscript: false
